spring:
  jmx:
    enabled: true
  kafka:
    bootstrapServers: ${BOOTSTRAP_SERVERS:localhost:9092}
    security.protocol: ${SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      trust-store-location: file://${SSL_TRUST_STORE_LOCATION_INTERNAL:/opt/kafkafhirvalidator/ssl/truststore.jks}
      trust-store-password: ${SSL_TRUST_STORE_PASSWORD}
      key-store-location: file://${SSL_KEY_STORE_LOCATION_INTERNAL:/opt/kafkafhirvalidator/ssl/keystore.jks}
      key-store-password: ${SSL_KEY_STORE_PASSWORD}
  docker:
    compose:
      enabled: false
  cloud:
    stream:
      function.definition: process
      bindings:
        process-in-0:
          destination: fhir-validation-input
        process-out-0:
          destination: fhir-validation-output
      kafka:
        streams:
          binder:
            applicationId: kafka-fhir-validator
            configuration:
              compression.type: gzip
              max.request.size: 5242880
app:
  profile-location: node_modules



management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "health, prometheus, info, metric"
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true

logging:
  level:
    org.springframework.kafka.config: info
    de.unimarburg.diz.kafkafhirvalidator: debug
