services:
  fhir-validator:
    image: docker.io/library/kafka-fhir-validator:0.0.2-SNAPSHOT
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      SPRING_CLOUD_STREAM_BINDINGS_PROCESS-IN-0_DESTINATION: ${FHIR_VALIDATION_INPUT1}
      SPRING_CLOUD_STREAM_BINDINGS_PROCESS-OUT-0_DESTINATION: ${FHIR_VALIDATION_OUTPUT1}
      SPRING_KAFKA_SECURITY_PROTOCOL: SSL
      SPRING_KAFKA_SSL_KEY_STORE_PASSWORD: ${FHIR_VALIDATION_KEY_STORE_PASSWORD}
      SPRING_KAFKA_SSL_TRUST_STORE_PASSWORD: ${KAFKA_TRUST_STORE_PASSWORD}
    ports:
      - "${FHIR_VALIDATION_PORT}:8080"
    volumes:
      - ${FHIR_VALIDATION_PROFILE_LOCATION:-?}:/workspace/node_modules
